### ISSUE TITLE
网络连接超时导致栈溢出

### ISSUE THREAD

**Issue by chenupt** [tencentyun/qcloud-sdk-android#1]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
对象存储put操作
* 您使用的SDK版本号是多少？
1.2.1.1
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机，wifi
* 使用更高版本的SDK是否解决了您的问题？
否
* 这个问题是否和特定的网络环境有关系？
否
* 您集成我们SDK的方式是什么？
jar包
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。

***

当连接超时，栈溢出，必现。

日志：
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                   at java.lang.Thread.run(Thread.java:764)
                                                                Caused by: java.lang.StackOverflowError: stack size 1038KB
                                                                   at java.lang.System.getProperty(System.java:1228)
                                                                   at sun.security.action.GetPropertyAction.run(GetPropertyAction.java:84)
                                                                   at sun.security.action.GetPropertyAction.run(GetPropertyAction.java:76)
                                                                   at java.security.AccessController.doPrivileged(AccessController.java:41)
                                                                   at java.io.PrintWriter.<init>(PrintWriter.java:116)
                                                                   at java.io.PrintWriter.<init>(PrintWriter.java:100)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:28)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:648)
                                                                   at java.lang.Throwable.printStackTrace(Throwable.java:713)
                                                                   at com.tencent.cos.xml.exception.CosXmlClientException.toString(CosXmlClientException.java:29)
                                                                   at java.lang.String.valueOf(String.java:2827)
                                                                   at java.io.PrintWriter.println(PrintWriter.java:754)
                                                                   at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:756)

```

**Comment by bradyxiao** [comment]
@chenupt 
这个栈溢出，是进入深度的循环导致的，CosXmlClientException.toString()内部调用了printStackTrace(Write), sdk已注释掉了
