### ISSUE TITLE
DNS 解析错误

### ISSUE THREAD

**Issue by CoenQian** [tencentyun/qcloud-sdk-android#13]
`cos..myqcloud.com` 这个是啥？可以屏蔽这种日志么，老以为 COS 的配置有问题。

```
10-18 16:00:54.005 17840 17860 W System.err: java.net.UnknownHostException: Unable to resolve host "cos..myqcloud.com": No address associated with hostname
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
10-18 16:00:54.005 17840 17860 W System.err: 	at okhttp3.Dns$1.lookup(Dns.java:40)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:262)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetchAll(ConnectionRepository.java:247)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$1.run(ConnectionRepository.java:129)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.lang.Thread.run(Thread.java:818)
10-18 16:00:54.005 17840 17860 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
10-18 16:00:54.005 17840 17860 W System.err: 	at libcore.io.Posix.android_getaddrinfo(Native Method)
10-18 16:00:54.005 17840 17860 W System.err: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
10-18 16:00:54.005 17840 17860 W System.err: 	... 9 more
10-18 16:00:54.005 17840 17860 W System.err: java.net.UnknownHostException: Unable to resolve host "cos..myqcloud.com": No address associated with hostname
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
10-18 16:00:54.005 17840 17860 W System.err: 	at okhttp3.Dns$1.lookup(Dns.java:40)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:262)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:265)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetchAll(ConnectionRepository.java:247)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$1.run(ConnectionRepository.java:129)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.lang.Thread.run(Thread.java:818)
10-18 16:00:54.005 17840 17860 W System.err: java.net.UnknownHostException: Unable to resolve host "cos..myqcloud.com": No address associated with hostname
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
10-18 16:00:54.005 17840 17860 W System.err: 	at okhttp3.Dns$1.lookup(Dns.java:40)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:262)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:265)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetch(ConnectionRepository.java:265)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$DnsFetcher.fetchAll(ConnectionRepository.java:247)
10-18 16:00:54.005 17840 17860 W System.err: 	at com.tencent.qcloud.core.http.ConnectionRepository$1.run(ConnectionRepository.java:129)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-18 16:00:54.005 17840 17860 W System.err: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by jordanqin** [comment]
日志中的cos..myqcloud.com域名确实不正常，建议检查下CosXmlServiceConfig以及请求参数是否正确。
另外如果不要日志的话，可以在CosXmlServiceConfig中setDebuggable(false)
