### ISSUE TITLE
多线程上传时报【java.lang.IllegalMonitorStateException】

### ISSUE THREAD

**Issue by WuFengXue** [tencentyun/qcloud-sdk-android#3]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
COS

* 您使用的SDK版本号是多少？
5.4.3

* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机，8.1.0，wifi

* 使用更高版本的SDK是否解决了您的问题？
否（5.4.7）

* 这个问题是否和特定的网络环境有关系？
否

* 您集成我们SDK的方式是什么？
gradle

* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
```
08-06 11:47:30.595 13187-13254/? E/AndroidRuntime: FATAL EXCEPTION: Thread-47
    Process: com.scrm.assistant, PID: 13187
    java.lang.IllegalMonitorStateException
        at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:152)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1285)
        at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:458)
        at com.tencent.qcloud.core.auth.BasicLifecycleCredentialProvider.refresh(BasicLifecycleCredentialProvider.java:46)
        at com.tencent.qcloud.core.auth.BasicLifecycleCredentialProvider.getCredentials(BasicLifecycleCredentialProvider.java:26)
        at com.tencent.qcloud.core.http.HttpTask.signRequest(HttpTask.java:158)
        at com.tencent.qcloud.core.http.HttpTask.onCommand(HttpTask.java:109)
        at com.tencent.qcloud.core.http.HttpTask.onCommand(HttpTask.java:29)
        at com.tencent.qcloud.core.task.Task.run(Task.java:234)
        at com.tencent.qcloud.core.task.CancelableTask.run(CancelableTask.java:28)
        at com.tencent.qcloud.core.task.Task.executeNowSilently(Task.java:77)
        at com.tencent.qcloud.core.task.Task.executeNow(Task.java:63)
        at com.tencent.cos.xml.CosXmlSimpleService.execute(CosXmlSimpleService.java:135)
        at com.tencent.cos.xml.CosXmlSimpleService.putObject(CosXmlSimpleService.java:381)
        at com.scrm.assistant.yun.TencentYun.uploadFile(TencentYun.java:250)
        at com.scrm.assistant.util.LogUploadUtil$1.run(LogUploadUtil.java:158)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by WuFengXue** [comment]
BasicLifecycleCredentialProvider.java 的 refresh() 方法，解锁时没有做判断

![image](https://user-images.githubusercontent.com/12031430/43699708-7017a284-9982-11e8-8f44-2b5ca03fc389.png)

**Comment by WuFengXue** [comment]
java 官方文档 tryLock 说明：

tryLock
boolean tryLock​()
Acquires the lock only if it is free at the time of invocation.
Acquires the lock if it is available and returns immediately with the value true. If the lock is not available then this method will return immediately with the value false.

A typical usage idiom for this method would be:

 ```
 Lock lock = ...;
 if (lock.tryLock()) {
   try {
     // manipulate protected state
   } finally {
     lock.unlock();
   }
 } else {
   // perform alternative actions
 }
```
This usage ensures that the lock is unlocked if it was acquired, and doesn't try to unlock if the lock was not acquired.
Returns:
true if the lock was acquired and false otherwise


建议只在成功获取到锁时才执行解锁操作

**Comment by konakonall** [comment]
@WuFengXue 感谢反馈，下个版本会修复该问题
