### ISSUE TITLE
Credentials is null.

### ISSUE THREAD

**Issue by hewjinxu** [tencentyun/qcloud-sdk-android#7]
### 为了帮助我们更好的解决您的问题，请您先回答下面的几个问题。

* 您使用的是我们的哪一种服务？
ComXml
* 您使用的SDK版本号是多少？
5.4.25
* 您当前的设备环境是什么样子的？[真机/模拟器？, 系统版本，网络环境....]
真机，JoyUI，WiFi
* 使用更高版本的SDK是否解决了您的问题？
已是最高版本
* 这个问题是否和特定的网络环境有关系？
未知
* 您集成我们SDK的方式是什么？
gradle集成'com.tencent.qcloud:cosxml-lite:5.4.25'
* 如果您有一个完整的重现该问题的步骤或者一个小的例子帮我们重现问题，请贴在下面（同时请您注明详细的网络环境等相关上下文信息，如果有相关的Log也请您附注上）。
08-04 17:55:09.044512 23928 27876 I QCloudHttp: Request{method=GET, url=http://sharktimeapi.blackshark.com:8085/V2/Sharktime/GetSign, tags={class java.lang.Object=HttpTask-com.tencent.qcloud.core.http.HttpRequest@2b49406-14}} start to testExecute, attempts is 0
08-04 17:55:09.049250 23928 27866 W System.err: com.tencent.cos.xml.exception.CosXmlClientException: com.tencent.qcloud.core.common.QCloudClientException: Credentials is null.
08-04 17:55:09.049436 23928 27866 W System.err: 	at com.tencent.cos.xml.CosXmlSimpleService$1.onFailure(CosXmlSimpleService.java:322)
08-04 17:55:09.049474 23928 27866 W System.err: 	at com.tencent.qcloud.core.task.QCloudTask.onFailure(QCloudTask.java:298)
08-04 17:55:09.049492 23928 27866 W System.err: 	at com.tencent.qcloud.core.task.QCloudTask$1$1.call(QCloudTask.java:109)
08-04 17:55:09.049506 23928 27866 W System.err: 	at com.tencent.qcloud.core.task.QCloudTask$1$1.call(QCloudTask.java:106)
08-04 17:55:09.049516 23928 27866 W System.err: 	at bolts.Task$4.run(Task.java:357)
08-04 17:55:09.049529 23928 27866 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-04 17:55:09.049549 23928 27866 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-04 17:55:09.049562 23928 27866 W System.err: 	at java.lang.Thread.run(Thread.java:764)
08-04 17:55:09.049629 23928 27866 W System.err: Caused by: com.tencent.qcloud.core.common.QCloudClientException: Credentials is null.
08-04 17:55:09.049657 23928 27866 W System.err: 	at com.tencent.qcloud.core.auth.COSXmlSigner.sign(COSXmlSigner.java:25)
08-04 17:55:09.049675 23928 27866 W System.err: 	at com.tencent.qcloud.core.http.HttpTask.signRequest(HttpTask.java:192)
08-04 17:55:09.049698 23928 27866 W System.err: 	at com.tencent.qcloud.core.http.HttpTask.execute(HttpTask.java:142)
08-04 17:55:09.049711 23928 27866 W System.err: 	at com.tencent.qcloud.core.http.HttpTask.execute(HttpTask.java:37)
08-04 17:55:09.049721 23928 27866 W System.err: 	at com.tencent.qcloud.core.task.QCloudTask.call(QCloudTask.java:179)
08-04 17:55:09.049731 23928 27866 W System.err: 	... 4 more
08-04 17:55:09.051267 23928 27876 I QCloudHttp: dns: sharktimeapi.blackshark.com:{182.254.xxx.xxx,}

**Comment by konakonall** [comment]
Credentials is null 通常表明没有拿到密钥，如果是临时密钥建议检查一下后端的服务请求是否能成功。

**Comment by hewjinxu** [comment]
这是一个传输过程中中间返回的错误，此时文件已经上传了53%了，然后返回了这个异常，导致流程终止，并不是一开始密钥就有问题
